# Generated by Django 5.0.1 on 2024-01-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First_Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last_Name', max_length=50)),
                ('user_name', models.CharField(db_column='User_Name', max_length=50, unique=True)),
                ('email', models.CharField(db_column='Email', max_length=100, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('date_of_birth', models.DateField(db_column='Date_Of_Birth')),
                ('created_on', models.DateTimeField(blank=True, db_column='Created_On', null=True)),
                ('modified_on', models.DateTimeField(blank=True, db_column='Modified_On', null=True)),
                ('profile_image', models.CharField(blank=True, db_column='Profile_Image', max_length=255, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, db_column='Deleted_On', null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
